Update and rename build-all to build-essentials, better describing what it does, improvments in update-all

diff --git a/build-essentials b/build-essentials
--- a/build-essentials
+++ b/build-essentials
@@ -81,6 +81,18 @@ if [ $? -ne 0 ]; then
   exit $?
 fi
 cd -
+cd portlets/liferay-ext
+echo "###############################################################################"
+echo "Building liferay-ext"
+echo "###############################################################################"
+mvn clean install
+if [ $? -ne 0 ]; then
+  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+  echo "Failed building liferay-ext!"
+  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+  exit $?
+fi
+cd -
 cd portlets/build
 mvn clean package
 mvn integration-test
